name: Alpha Release
on:
  push:

jobs:
  bigwigs_github_alpha_release:
    name: Build via BigWigs packager for GitHub only
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Get name of zip file
        run: echo "artifact=`readlink -f *.md`" >> $GITHUB_ENV
      - name: Create name of release
        run: echo "RELEASENAME=`git describe --abbrev=0 --tags HEAD`-${{ env.GITHUB_SHA }}" >> $GITHUB_ENV
      - name: ECHO
        run: echo ${{ env.ARTIFACT }} ${{ env.RELEASENAME }}
      - name: Create Release and upload artifact to GitHub
        uses: ncipollo/release-action@v1
        with:
          name: ${{ env.RELEASENAME }}
          tag: ${{ env.RELEASENAME }}
          artifacts: ${{ env.ARTIFACT }}
          prerelease: true
          token: ${{ secrets.GITHUB_TOKEN }}
